"""test:

Revision ID: 42cb43280446
Revises: 2c52ac33c760
Create Date: 2020-07-23 21:49:41.188282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42cb43280446'
down_revision = '2c52ac33c760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ELECTRO', 'Hueter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ELECTRO', sa.Column('Hueter', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
